---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
data:
  datasources.yaml: |-
    {
      "apiVersion": 1,
      "deleteDatasources": [
        {
          "name": "mimir"
        },
        {
          "name": "tempo"
        },
        {
          "name": "prometheus"
        },
        {
          "name": "Loki"
        }
      ],
      "datasources": [
        {
          "name": "mimir",
          "type": "prometheus",
          "uid": "kentbank-mimir",
          "access": "proxy",
          "url": "http://mimir-nginx.mimir.svc:80/prometheus",
          "basicAuth": true,
          "basicAuthUser": "kentbank",
          "editable": true,
          "jsonData": {
            "httpHeaderName1": "X-Scope-OrgID"
          },
          "secureJsonData": {
            "basicAuthPassword": "awsome",
            "httpHeaderValue1": "kentbank"
          }
        },
        {
          "name": "tempo",
          "type": "tempo",
          "uid": "kentbank-tempo",
          "access": "proxy",
          "url": "http://tempo.tempo.svc:3100",
          "isDefault": false,
          "version": 1,
          "editable": true,
          "basicAuth": true,
          "basicAuthUser": "kentbank",
          "jsonData": {
            "httpHeaderName1": "X-Scope-OrgID"
          },
          "secureJsonData": {
            "basicAuthPassword": "awsome",
            "httpHeaderValue1": "kentbank"
          }
        },
        {
          "name": "Loki",
          "type": "loki",
          "access": "proxy",
          "uid": "kentbank-loki",
          "url": "http://loki.loki.svc:3100",
          "basicAuth": true,
          "basicAuthUser": "kentbank",
          "editable": true,
          "jsonData": {
            "httpHeaderName1": "X-Scope-OrgID",
            "derivedFields": [
              {
                "datasourceUid": "kentbank-tempo",
                "matcherRegex": '((\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+))',
                "name": "TraceID",
                "url": "$${__value.raw}"
              }
            ]
          },
          "secureJsonData": {
            "basicAuthPassword": "awsome",
            "httpHeaderValue1": "kentbank"
          }
        }
      ]
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard
  namespace: grafana
data:
  dashboard.json : |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "loki",
            "uid": "O_WAUNLVk"
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "dedupStrategy": "none",
            "enableLogDetails": true,
            "prettifyLogMessage": false,
            "showCommonLabels": false,
            "showLabels": false,
            "showTime": false,
            "sortOrder": "Descending",
            "wrapLogMessage": false
          },
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "O_WAUNLVk"
              },
              "editorMode": "builder",
              "expr": "{container=\"argocd-repo-server\"} |= ``",
              "key": "Q-179c5770-b82d-4cb4-8ab4-9920258a8aab-0",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "New Panel",
          "type": "logs"
        }
      ],
      "schemaVersion": 37,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "BibinJsonTest123",
      "uid": "Z6RmGKL4z123",
      "version": 1,
      "weekStart": ""
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: false
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-dashboard
              readOnly: false
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
        - name: grafana-dashboard
          configMap:
            defaultMode: 420
            name: grafana-dashboard

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer

